-- 1. DROP EXISTING
DROP TABLE IF EXISTS deliveries CASCADE;
DROP TABLE IF EXISTS matches CASCADE;

-- 2. CREATE MATCHES
CREATE TABLE matches (
    match_id         TEXT PRIMARY KEY,
    match_date       DATE NOT NULL,
    season           TEXT,
    city             TEXT,
    venue            TEXT,
    team1            TEXT,
    team2            TEXT,
    toss_winner      TEXT,
    toss_decision    TEXT,
    winner           TEXT,
    result_type      TEXT,
    result_margin    INTEGER,
    player_of_match  TEXT
);

-- 3. CREATE DELIVERIES
CREATE TABLE deliveries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id      TEXT NOT NULL REFERENCES matches(match_id) ON DELETE CASCADE,
    inning        INTEGER NOT NULL,
    over          INTEGER NOT NULL,
    ball          INTEGER NOT NULL,
    batting_team  TEXT,
    bowling_team  TEXT,
    batter        TEXT,
    bowler        TEXT,
    non_striker   TEXT,
    runs_batter   INTEGER DEFAULT 0,
    runs_extras   INTEGER DEFAULT 0,
    runs_total    INTEGER DEFAULT 0,
    wicket_type   TEXT,
    player_out    TEXT,
    extra_type    TEXT,
    CONSTRAINT unique_ball_delivery UNIQUE (match_id, inning, "over", ball)
);

-- 4. INDEXES
CREATE INDEX idx_deliveries_match_id ON deliveries(match_id);
CREATE INDEX idx_deliveries_batter ON deliveries(batter);
CREATE INDEX idx_deliveries_bowler ON deliveries(bowler);

-- ==========================================
-- 5. SECURITY & RLS (Fixes Supabase Warning)
-- ==========================================

-- Enable Row Level Security
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;

-- Create Public Read-Only Policies
-- This allows your Streamlit app to fetch data but prevents unauthorized DELETES/UPDATES
CREATE POLICY "Allow public read access" ON matches FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON deliveries FOR SELECT USING (true);