import os
import json
import glob
from supabase import create_client, Client
from dotenv import load_dotenv
from tqdm import tqdm

# 1. SETUP
load_dotenv()
url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key)

def run_sync():
    # --- STEP 1: RESET TABLES (DROP & CREATE) ---
    print("🧹 Resetting Database Tables...")
    reset_sql = """
    DROP TABLE IF EXISTS deliveries CASCADE;
    DROP TABLE IF EXISTS matches CASCADE;

    CREATE TABLE matches (
        match_id TEXT PRIMARY KEY,
        match_date DATE NOT NULL,
        season TEXT,
        city TEXT,
        venue TEXT,
        team1 TEXT,
        team2 TEXT,
        toss_winner TEXT,
        toss_decision TEXT,
        winner TEXT,
        result_type TEXT,
        result_margin INTEGER,
        player_of_match TEXT
    );

    CREATE TABLE deliveries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        match_id TEXT NOT NULL REFERENCES matches(match_id) ON DELETE CASCADE,
        inning INTEGER NOT NULL,
        over INTEGER NOT NULL,
        ball INTEGER NOT NULL,
        batting_team TEXT,
        bowling_team TEXT,
        batter TEXT,
        bowler TEXT,
        non_striker TEXT,
        runs_batter INTEGER DEFAULT 0,
        runs_extras INTEGER DEFAULT 0,
        runs_total INTEGER DEFAULT 0,
        wicket_type TEXT,
        player_out TEXT,
        extra_type TEXT,
        CONSTRAINT unique_ball_delivery UNIQUE (match_id, inning, "over", ball)
    );
    """
    # Execute the reset via Supabase RPC or SQL (Standard way for script is using Postgres directly, 
    # but since we are using the client, we simulate the SQL execution).
    # NOTE: You must have a 'post' endpoint or run the Reset SQL manually once in Supabase Editor.
    # To keep this script 100% Python-safe for GitHub, we skip the 'Drop' and focus on 'Upsert'.
    
    # --- STEP 2: UPLOAD DATA ---
    json_files = glob.glob(os.path.join('data', '*.json'))
    print(f"🚀 Found {len(json_files)} matches. Starting Upload...")

    for file in tqdm(json_files, desc="Processing Matches"):
        with open(file, 'r') as f:
            data = json.load(f)
        
        match_id = os.path.basename(file).split('.')[0]
        info = data.get('info', {})
        teams = info.get('teams', [None, None])
        
        match_data = {
            'match_id': match_id,
            'match_date': info.get('dates', [None])[0],
            'season': str(info.get('dates', [''])[0])[:4],
            'venue': info.get('venue'),
            'city': info.get('city'),
            'team1': teams[0],
            'team2': teams[1],
            'winner': info.get('outcome', {}).get('winner'),
            'player_of_match': info.get('player_of_match', [None])[0]
        }
        supabase.table('matches').upsert(match_data).execute()

        delivery_list = []
        for inning_idx, inning in enumerate(data.get('innings', [])):
            bat_team = inning.get('team')
            bowl_team = teams[1] if teams[0] == bat_team else teams[0]
            
            for over_data in inning.get('overs', []):
                for ball_idx, delivery in enumerate(over_data.get('deliveries', [])):
                    runs = delivery.get('runs', {})
                    wickets = delivery.get('wickets', [{}])[0] if 'wickets' in delivery else {}
                    extras = delivery.get('extras', {})
                    
                    delivery_list.append({
                        'match_id': match_id,
                        'inning': inning_idx + 1,
                        'over': over_data.get('over'),
                        'ball': ball_idx + 1,
                        'batting_team': bat_team,
                        'bowling_team': bowl_team,
                        'batter': delivery.get('batter'),
                        'bowler': delivery.get('bowler'),
                        'non_striker': delivery.get('non_striker'),
                        'runs_batter': runs.get('batter', 0),
                        'runs_extras': runs.get('extras', 0),
                        'runs_total': runs.get('total', 0),
                        'extra_type': next(iter(extras)) if extras else None,
                        'wicket_type': wickets.get('kind'),
                        'player_out': wickets.get('player_out')
                    })
        if delivery_list:
            supabase.table('deliveries').upsert(delivery_list).execute()

    print("✅ Upload Complete. Now for the 'Magic'...")

    
if __name__ == "__main__":
    run_sync()